theme = "dracula"
client_port = 8080
login_redirect_uri = "http://127.0.0.1:8989/login"
playback_format = """
{status}{track} {liked}
{artists}
{album}
{metadata}"""
playback_metadata_fields = [
    "repeat",
    "shuffle",
]
notify_timeout_in_secs = 0
tracks_playback_limit = 200
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
page_size_in_rows = 40
play_icon = ""
pause_icon = "▶ "
liked_icon = "♥"
border_type = "Rounded"
progress_bar_type = "Rectangle"
progress_bar_position = "Bottom"
genre_num = 2
cover_img_length = 9
cover_img_width = 4
cover_img_scale = 1.0
enable_media_control = true
enable_streaming = "Always"
enable_notify = true
enable_cover_image_cache = false
default_device = "spotify-player"
notify_streaming_only = false
seek_duration_secs = 10
sort_artist_albums_by_type = false

[notify_format]
summary = "{track} • {artists}"
body = "{album}"

[layout]
playback_window_position = "Top"
playback_window_height = 4

[layout.library]
playlist_percent = 40
album_percent = 40

[device]
name = "spotify-player"
device_type = "speaker"
volume = 100
bitrate = 320
audio_cache = false
normalization = true
autoplay = false
