add_newline = true

format = """
$shell\
$directory\
$fill\
$git_branch\
$git_state\
$git_status\
$java\
$cpp\n\
$character"""

[shell]
disabled = false
format = 'on [$indicator]($style) | '
zsh_indicator = '[zsh](purple)'
fish_indicator = '[fish](cyan)'

[directory]
truncate_to_repo = true

[directory.substitutions]
"Documents" = "Docs."
"Downloads" = "Down."
"Developer" = "Dev."

[fill]
symbol = ' '
style = 'bold white'

[git_branch]
disabled = false

[git_state]
disabled = false

[git_status]
disabled = false

[cpp]
disabled = false

[java]
disabled = false

