[[mgr.append_keymap]]
on = [ "c", "i" ]
run = "shell '~/.config/scripts/copy_image.sh \"$0\"'"
desc = "Copy hovered image to clipboard"

[[mgr.append_keymap]]
on = "<S-Up>"
run = "arrow -5"
desc = "Move cursor down 5 lines"

[[mgr.append_keymap]]
on = "<S-Down>"
run = "arrow 5"
desc = "Move cursor up 5 lines"

[[mgr.prepend_keymap]]
on = [ "M" ]
run = "plugin relative-motions"
desc = "Trigger a new relative motion"

[[mgr.prepend_keymap]]
on  = "q"
run = "plugin confirm-quit"

