#!/bin/zsh

pokemon_sprite() {
   # Set path to the sprited folder
   sprite_folder="$HOME/.config/zsh/sprites"

   # Get all files in the sprite folder
   sprite_files=("$sprite_folder"/*)

   # Generate a random index
   count=${#sprite_files[@]}
   random_index=$(( RANDOM % count ))

   # Print the sprite
   echo ''
   cat "${sprite_files[$random_index]}"
}
